version: "3.9"
services:
  db:
    build:
      context: ./data/src/main/resources/mariadb/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: hummer
      MARIADB_DATABASE: smart
    ports:
      - "3350:3306"

